# Base configs
baseurl: "https://roshkphotography.github.io/Photofolio"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by RoshK"
subtitle: "See the world through my eyes!"
author: "RoshK"
header:
 title: "Photography"
 subtitle: "by RoshK"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a software developer and a tech aficionado. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/photography\">fork this repo on github</a> ;)"
web_design: "AJ"

social_urls:
  twitter: "https://www.twitter.com/RoshK_"
  instagram: "https://www.instagram.com/RoshK"
  dribbble: "https://dribbble.com/RoshK"
  linkedin: "https://in.linkedin.com/in/RoshK"
  github: "https://www.github.com/RoshK"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'